// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-AfUB2UHLDUWsFEcjLYjHxXh0UtYZfE',
    appId: '1:265348681220:android:8469427042ee82ed17ef51',
    messagingSenderId: '265348681220',
    projectId: 'symonskitechen',
    storageBucket: 'symonskitechen.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Nx9i_MXY7hLVtMw5IhEPu7CR5RSEVD0',
    appId: '1:265348681220:ios:e8ac1e39bcfd782217ef51',
    messagingSenderId: '265348681220',
    projectId: 'symonskitechen',
    storageBucket: 'symonskitechen.firebasestorage.app',
    iosBundleId: 'com.symonskitchin.symonsApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXdiIyqUwnQWhjIJBhHR_J0RDJksgcQFQ',
    appId: '1:265348681220:web:ce4b833879c037d017ef51',
    messagingSenderId: '265348681220',
    projectId: 'symonskitechen',
    authDomain: 'symonskitechen.firebaseapp.com',
    storageBucket: 'symonskitechen.firebasestorage.app',
    measurementId: 'G-DG3JXSFJXJ',
  );
}
